#!/usr/bin/env python
# Copyright (c) 2026, Salesforce, Inc.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generate the paper's synthetic-mechanism tables from raw per-instance data.

Emits (into the paper repo's tables/):
  synth_storage.tex  — single-needle: where and in what form the needle survives
  synth_twofact.tex  — two needles: how their storage placement interacts

Numbers are computed here, never transcribed. Cohort policy (REGISTERED.md 07-31): the
later fresh-seeded runs are canonical for exact-retrieval numbers; earlier-run rows are
marked with a dagger in the table and are the only source for the single-head and
depth conditions. Rep-pooled per instance where replicates exist.

Usage: gen_synth_tables.py [--out <paper tables dir>]
"""
import argparse
import json
import os

import numpy as np

O = os.path.join(os.environ.get("RA_ROOT", "."), "results/synth_runs")
BOOT = 4000
rng = np.random.default_rng(20260731)


def load(cell, arm, gok=False):
    p = f"{O}/{cell}/{arm}.jsonl"
    if not (os.path.exists(p) and os.path.exists(f"{O}/{cell}/{arm}.done")):
        return None
    rs = sorted((json.loads(l) for l in open(p)), key=lambda r: r["i"])
    d = {"i": np.array([r["i"] for r in rs]),
         "lp": np.array([r["lp_sum"] for r in rs]),
         "acc": np.array([r["fg_ok"] for r in rs], dtype=float)}
    if gok:
        d["gok"] = np.array([r["gok"] for r in rs], dtype=bool)
    return d


def pooled(cell, arm, reps=("_r0", "_r1"), gok=False):
    """Rep-pooled per-instance arrays; falls back to the un-suffixed single run."""
    ds = [load(cell, arm + r, gok) for r in reps]
    if any(d is None for d in ds):
        d = load(cell, arm, gok)
        if d is None:
            return None
        ds = [d]
    idx = sorted(set.intersection(*(set(d["i"].tolist()) for d in ds)))
    out = {"i": np.array(idx)}
    for k in ("lp", "acc"):
        out[k] = np.mean([d[k][np.isin(d["i"], idx)] for d in ds], axis=0)
    if gok:
        NV = ds[0]["gok"].shape[1]
        out["accx"] = np.mean([d["gok"][np.isin(d["i"], idx)][:, 0:4].all(1) for d in ds], axis=0)
        out["accy"] = np.mean([d["gok"][np.isin(d["i"], idx)][:, NV - 4:NV].all(1) for d in ds],
                              axis=0)
    return out


def R_of(arm, h0, h8, ci=False):
    idx = sorted(set(arm["i"]) & set(h0["i"]) & set(h8["i"]))
    a, z, e = (d["lp"][np.isin(d["i"], idx)] for d in (arm, h0, h8))
    r = float((a - z).sum() / (e - z).sum())
    if not ci:
        return r
    n = len(a)
    v = []
    for _ in range(BOOT):
        k = rng.integers(0, n, n)
        den = (e[k] - z[k]).sum()
        if den:
            v.append((a[k] - z[k]).sum() / den)
    return r, float(np.percentile(v, 2.5)), float(np.percentile(v, 97.5))


def acc_ci(a):
    n = len(a)
    v = [a[rng.integers(0, n, n)].mean() for _ in range(BOOT)]
    return a.mean(), np.percentile(v, 2.5), np.percentile(v, 97.5)


def fmt(x, nd=3):
    return f"${x:.{nd}f}$" if x is not None and np.isfinite(x) else "---"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.environ.get("RA_ROOT", "."), "tables"))
    args = ap.parse_args()

    h0, h8 = load("a1536", "h0"), load("a1536", "h8")
    f0, f8 = load("a1536_fragv", "fragv_h0"), load("a1536_fragv", "fragv_h8")

    def row(label, cell, arm, endpoints=("a1536",), dagger=False, reps=("_r0", "_r1")):
        d = pooled(cell, arm, reps=reps)
        if d is None:
            return None
        e0, e8 = (h0, h8) if endpoints[0] == "a1536" else (f0, f8)
        r, rlo, rhi = R_of(d, e0, e8, ci=True)
        m, lo, hi = acc_ci(d["acc"])
        mark = "$^{\\dagger}$" if dagger else ""
        return (f"{label}{mark} & {fmt(m)} & $[{lo:.2f},\\,{hi:.2f}]$ & {fmt(r)} & "
                f"$[{rlo:.2f},\\,{rhi:.2f}]$ & ${len(d['i'])}$ \\\\")

    # ---------------- Table 1: compact single-needle storage --------------------------
    def crow(label, cell, arm, endpoints=("a1536",), reps=("_r0", "_r1")):
        d = pooled(cell, arm, reps=reps)
        if d is None:
            return None
        e0, e8 = (h0, h8) if endpoints[0] == "a1536" else (f0, f8)
        return f"{label} & {fmt(d['acc'].mean(), 2)} & {fmt(R_of(d, e0, e8), 2)} \\\\"

    L = []
    L.append("% AUTO-GENERATED by kvcompress/synth/gen_synth_tables.py -- do not hand-edit.")
    L.append("\\begin{wraptable}{r}{0.51\\textwidth}")
    L.append("\\vspace{-1.2\\baselineskip}")
    L.append("\\centering")
    L.append("\\footnotesize")
    L.append("\\caption{Retrieval and recall of the planted fact by what "
             "survives.}")
    L.append("\\label{tab:synthstorage}")
    L.append("\\begin{tabular}{lcc}")
    L.append("\\toprule")
    L.append("What survives & Retr. & $R$ \\\\")
    L.append("\\midrule")
    L.append(crow("restatement (original deleted)", "a1536_wakeR", "wake_natural", reps=("",)))
    L.append(crow("derived mention (original deleted)", "a1536_wakeD", "wake_natural", reps=("",)))
    L.append("@@MEANPAIR@@")
    L.append(crow("single tokens, spread", "a1536", "s3_frag2_rot"))
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\vspace{-0.8\\baselineskip}")
    L.append("\\end{wraptable}")

    # weighted-mean row (mass-matched comparator for the fragmentation contrast)
    a25, a35, a23, fr = (pooled("a1536", a) for a in
                         ("s3_intact2_25", "s3_intact2_35", "s3_intact2_23", "s3_frag2_rot"))
    idx = sorted(set(a25["i"]) & set(a35["i"]) & set(a23["i"]) & set(fr["i"]))
    sel = lambda d, k="acc": d[k][np.isin(d["i"], idx)]
    mp = (12 * sel(a25) + 10 * sel(a35) + 10 * sel(a23)) / 32
    mpR = (12 * R_of(a25, h0, h8) + 10 * R_of(a35, h0, h8) + 10 * R_of(a23, h0, h8)) / 32
    m, lo, hi = acc_ci(mp)
    L[L.index("@@MEANPAIR@@")] = (
        f"whole sentence, in 2 heads & {fmt(m, 2)} & {fmt(mpR, 2)} \\\\")
    D = sel(fr) - mp
    n = len(D)
    lbD = np.percentile([D[rng.integers(0, n, n)].mean() for _ in range(BOOT)], 5)
    print(f"[check] fragmentation cost vs mass-matched intact: {D.mean():+.3f} "
          f"(one-sided 95% LB {lbD:+.3f})")

    open(os.path.join(args.out, "synth_storage.tex"), "w").write(
        "\n".join(x for x in L if x) + "\n")

    # ---------------- Table 2: two needles --------------------------------------------
    T = []
    T.append("% AUTO-GENERATED by kvcompress/synth/gen_synth_tables.py -- do not hand-edit.")
    T.append("\\begin{table}[t]")
    T.append("\\centering")
    T.append("\\footnotesize")
    T.append("\\caption{Two needles in one trace, both requested at the end (Qwen3-4B, "
             "$n{=}500$ per row, exact retrieval scored separately for each needle). "
             "Needle $x$ is planted first and $y$ $256$ tokens later, so $y$ is the younger "
             "of the two; comparisons are made within a needle, down a column. Sharing one "
             "pair of storage heads costs both needles most of their retrieval.}")
    T.append("\\label{tab:synthtwofact}")
    T.append("\\begin{tabular}{lcc}")
    T.append("\\toprule")
    T.append("Storage of the two needles & Retrieval of $x$ & Retrieval of $y$ \\\\")
    T.append("\\midrule")

    def trow(label, arm, reps=("_r0", "_r1")):
        d = pooled("a1536_s2r", arm, reps=reps, gok=True)
        if d is None:
            return None
        return f"{label} & {fmt(d['accx'].mean())} & {fmt(d['accy'].mean())} \\\\"

    T.append(trow("Both retained in every cache", "g_both_all", reps=("",)))
    T.append(trow("Both deleted everywhere", "g_none", reps=("",)))
    T.append("\\addlinespace")
    T.append(trow("Both in heads $\\{2,5\\}$", "r2_co25_b"))
    T.append(trow("$x$ in $\\{2,5\\}$, $y$ in $\\{1,3\\}$", "r2_split_x_b"))
    T.append(trow("$x$ in $\\{1,3\\}$, $y$ in $\\{2,5\\}$", "r2_split_y_b"))
    T.append(trow("$x$ in $\\{2,5\\}$, $y$ deleted everywhere", "r2_cap_solo"))
    T.append("\\addlinespace")
    T.append("\\multicolumn{3}{l}{\\emph{Fragmented storage (with its own control row)}} \\\\")
    T.append(trow("Both in heads $\\{2,5\\}$", "r3_co25_c"))
    T.append(trow("$y$ split across the pairs, $x$ in $\\{1,7\\}$", "r3_f3b"))
    T.append(trow("$x$ split across the pairs, $y$ in $\\{1,7\\}$", "r3_f3a"))
    T.append("\\bottomrule")
    T.append("\\end{tabular}")
    T.append("\\end{table}")
    open(os.path.join(args.out, "synth_twofact.tex"), "w").write(
        "\n".join(x for x in T if x) + "\n")

    B = []
    B.append("% AUTO-GENERATED by kvcompress/synth/gen_synth_tables.py -- do not hand-edit.")
    B.append("\\begin{wraptable}{r}{0.44\\textwidth}")
    B.append("\\vspace{-1.2\\baselineskip}")
    B.append("\\centering")
    B.append("\\small")
    B.append("\\caption{A passcode stated once, $57$ compression rounds before the "
             "question.}")
    B.append("\\label{tab:synthboundary}")
    B.append("\\setlength{\\tabcolsep}{4pt}")
    B.append("\\begin{tabular}{lcc}")
    B.append("\\toprule")
    B.append("Policy & Retr. & $\\log p$ \\\\")
    B.append("\\midrule")
    for lab, arm in [("\\method{} (ours)", "nat_rp"), ("\\vase{}", "s4_vase"),
                     ("\\snapkv{}", "s4_snapkv"), ("\\rkv{}", "s4_rkv"),
                     ("\\triattn{}", "s4_triattn")]:
        d = pooled("adeep_s4", arm, reps=("",))
        if d is not None:
            B.append(f"{lab} & {fmt(d['acc'].mean())} & {fmt(d['lp'].mean(), 2)} \\\\")
    B.append("\\bottomrule")
    B.append("\\end{tabular}")
    B.append("\\vspace{-1.0\\baselineskip}")
    B.append("\\end{wraptable}")
    open(os.path.join(args.out, "synth_boundary.tex"), "w").write(
        "\n".join(x for x in B if x) + "\n")

    print(f"wrote {args.out}/synth_storage.tex, synth_twofact.tex and synth_boundary.tex")


if __name__ == "__main__":
    main()
